Update patch set 3
Patch Set 3:

docs-rtd verify is broken on lf-build2 with 'ImportError: cannot import name main', which was most likely caused by the previous job (Fuel docker build) that ran on lf-build2 and included a pipenv upgrade [1].
I will look into it later, pip is really not my cup of tea.
[1] https://github.com/opnfv/fuel/commit/54164b84abc2b6b8772d2ac083e11ce7c137cc7c

Patch-set: 3